services:
  ros:
    build: .
    container_name: ros2
    volumes:
      - ./:/ros_ws
    tty: true
    stdin_open: true
    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
